version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Current directory:$(pwd)"
      - echo "Listing files:"
      - ls -R
      - echo "Deploying Glue script to S3..."
      - aws s3 cp glue_jobs/my_etl_job.py s3://github-glue-etl-script/glue_jobs/my_etl_job.py
