name: Deploy AWS Glue Job

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Glue script to S3
        run: |
          aws s3 cp glue_jobs/my_etl_job.py s3://git-glue-s3/glue_jobs/my_etl_job.py

      - name: Update AWS Glue job
        run: |
          aws glue update-job --job-name my-glue-job \
          --job-update '{
            "Command": {
              "Name": "glueetl",
              "ScriptLocation": "s3://git-glue-s3/glue_jobs/my_etl_job.py"
            }
          }'
